server:
  port: 8089
spring:
  application:
    name: bookingservice
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.eventsourcing.bookingservice.serializer.MessageSerializer
    consumer:
      key-deserializer: com.eventsourcing.bookingservice.deserializer.StringDeserializer
      value-deserializer: com.eventsourcing.bookingservice.deserializer.MessageDeserializer