spring:
  application:
    name: flightavailabilityservice
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.eventsourcing.flightavailabilityservice.deserializer.FlightAvailabilityDeSerializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.eventsourcing.flightavailabilityservice.serializer.MessageSerializer
server:
  port: 8081